# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  checkout_code:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          key: v1-dependencies-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/repo
  
  bundle_dependencies:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo
    steps:
      - restore_cache:
        key: v1-dependencies-{{ .Environment.CIRCLE_SHA1 }}

      - run: yarn install
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
            

workflows:
  version: 2
  build_and_test:
    jobs:
      - checkout_code
      - bundle_dependencies:
        requires:
          - checkout_code
