# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  checkout_code:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
        key: v1-dependencies-{{ .Environment.CIRCLE_SHA1 }}
        paths:
          - ~/repo

  bundle_dependencies:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo
    steps:
      - restore_cache:
        key: v1-dependencies-{{ .Environment.CIRCLE_SHA1 }}

      - run: yarn install
      - save_cache:
        key: v1-dependencies-{{ checksum "package.json" }}
        paths:
          - node_modules

  unit_test:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo
    steps:
      - restore_cache:
        key: v1-dependencies-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
        key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn test

  deploy_stage:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo
    steps:
      - restore_cache:
        key: v1-dependencies-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
        key: v1-dependencies-{{ checksum "package.json" }}

      - run:
        name: apt install python-pip python-dev
        command: sudo apt install python-pip python-dev

      - run:
        name: pip install awscli
        command: sudo pip install awscli

      - run:
        name: Deploy to S3 if tests pass and branch is master
        command: sh deploy.sh --env stage
  
  deploy_dev:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo
    steps:
      - restore_cache:
        key: v1-dependencies-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
        key: v1-dependencies-{{ checksum "package.json" }}

      - run:
        name: apt install python-pip python-dev
        command: sudo apt install python-pip python-dev

      - run:
        name: pip install awscli
        command: sudo pip install awscli

      - run:
        name: Deploy to S3 if tests pass and branch is develop
        command: sh deploy.sh --env dev


workflows:
  version: 2
  build-and-deploy:
    jobs:
      - checkout_code
      - bundle_dependencies:
        requires:
          - checkout_code
